name: "Update changelog and open a pull request"

on:
  workflow_dispatch:
    inputs:
      fname_changelog:
        description: 'Changelog filename'
        required: true
        default: 'CHANGES.md'
      milestone_title:
        description: 'Milestone title'
        required: true

jobs:
  create-changelog-PR:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python (to install 'changelog')
      uses: actions/setup-python@v2
    - name: Install 'changelog'
      run: |
        pip install git+https://github.com/neuropoly/changelog@master
    - name: Checkout '${{ github.event.repository.name }}'
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}
    - name: Update '${{ github.event.inputs.fname_changelog }}' for '${{ github.event.repository.name }}'
      run: |
        cd ${{ github.event.repository.name }}
        changelog spinalcordtoolbox/spinalcordtoolbox --update --name "${{ github.event.inputs.fname_changelog }}" --milestone ${{ github.event.inputs.milestone_title }} --use-milestone-due-date
        rm -f "${{ github.event.inputs.fname_changelog }}.bak"
    - name: Create pull request for updated changelog
      uses: peter-evans/create-pull-request@v3
      with:
        path: "${{ github.event.repository.name }}"
        branch: "bot/v${{ github.event.inputs.milestone_title }}"
        commit-message  : "Update ${{ github.event.inputs.fname_changelog }} for ${{ github.event.inputs.milestone_title }} release"
        title: "Update ${{ github.event.inputs.fname_changelog }} for ${{ github.event.inputs.milestone_title }} release"
        milestone: "${{ github.event.inputs.milestone_title }}"
        body: |
          Update ${{ github.event.inputs.fname_changelog }} for ${{ github.event.inputs.milestone_title }} release.
          
          Carried out as a part of the [release](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release) checklist.
        delete-branch: true
